- name: Install essential packages
  become: true
  ansible.builtin.package:
    name:
      - git
      - curl
      - base-devel

      - pipewire
      - wireplumber
      - mesa
      - power-profiles-daemon
      - pipewire-pulse
      - polkit-gnome
      - xdg-utils
      - xorg-xwayland

      - mako
      - sddm
      - niri
      - ttf-jetbrains-mono-nerd
      - ghostty
      - dolphin
      - amd-ucode
      - efibootmgr
      - grub
      - linux
      - linux-firmware
      - networkmanager
      - network-manager-applet

    state: present

- name: Ensure /etc/sudoers.d exists
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: '0750'

- name: Copy sudoers rule for paru
    become: true
    ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/.local/share/chezmoi/etc_sudoers.d/10-murc-paru"
    dest: /etc/sudoers.d/10-murc-paru
    mode: '0440'
    owner: root
    group: root
    validate: /usr/sbin/visudo -cf %s

- name: Check if paru is installed
  become: false
  ansible.builtin.command:
    cmd: which paru
  register: paru_check
  failed_when: false
  changed_when: false

- name: Clone paru repository
  ansible.builtin.git:
    repo: https://aur.archlinux.org/paru.git
    dest: "{{ ansible_env.HOME }}/paru"
  when: paru_check.rc != 0
  become: false

- name: Build and install paru
  become: false
  ansible.builtin.command:
    cmd: makepkg -si --noconfirm
    chdir: "{{ ansible_env.HOME }}/paru"
  when: paru_check.rc != 0
  changed_when: false

- name: Remove paru build directory
  become: true
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/paru"
    state: absent
  when: paru_check.rc != 0
  
